### ISSUE TITLE
pretty/colored output?

### ISSUE THREAD

**Issue by jgallen23** [sportngin/good-json-console#2]
Would you be interested in a pull request that adds an option for pretty output?  I was thinking about using this lib: https://www.npmjs.com/package/purdy. Let me know if you want a PR or if I should make a separate lib.

**Comment by mikefrey** [comment]
@jgallen23 I hesitate to add pretty output since the goal of this is really to provide a clean interface for consumption by another process.

It might be a better approach to pipe the output through another process that makes it pretty if that's what you want.
